config/routes.rb
TestApp::Application.routes.draw do
  devise_for :users

  # devise_scope :user do
  #   root :to => 'devise/sessions#new'
  # end
  devise_scope :user do
    authenticated :user do      
       root :to => 'users#index'
    end

    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end

    resources :users_admin, :controller => 'users'

    post "import_data" => "users"
    get "show" => "users#show"
    delete "destroy" => "users#destroy"
    get "compose_message" => "users"
    post "send_email" => "users"
    post "search_result" => "users"
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:name,:picture,:is_admin,:picture_name,:designation
  # attr_accessible :title, :body

  scope :check_user,where(:is_admin => false).order('id desc')
  
  acts_as_messageable

  def self.create_records name,designation,picture
  	email = name+"@letsgomo.com"
  	pic_name = name+"_"+designation+".jpg"
  	User.create(:name=>name,:designation=>designation,:picture=>picture,:picture_name=>pic_name.downcase,:email=>email.downcase,:password=>"12345678")
  end

  def self.search params
    User.where("users.name ILIKE :term OR users.designation ILIKE :term", :term => "%#{params}%" ) 
  end

  # You'd, probably, want to have a separate name column instead
  def name
    email
  end

  def mailboxer_email(object)
    email
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  #before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def create
    recipient_emails = conversation_params(:recipients).split(',')    
    recipients = User.where(email: recipient_emails).all    
    conversation = current_user.send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation_path(conversation)
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/controllers/users_controller.rb
require 'nokogiri'
require 'open-uri'

class UsersController < ApplicationController
	def index
		if params[:q]
			@users = User.search(params[:q])
		else
			@users = User.check_user
		end
		respond_to do |format|
      		format.html # index.html.erb 
      		format.js   # index.js.erb  
    	end
	end

	def show	
    @user = User.find(params[:id])
	    respond_to do |format|
	      format.html # show.html.erb	      
	    end
  	end

  	def destroy
    @user = User.find(params[:id])
    @user.destroy

	    respond_to do |format|
	      format.html { redirect_to root_path }	      
	    end
	 end

	 def compose_message
	 	
	 end

	 def send_email
	 	@user = User.find_by_email(params[:email])	 	  
		  path_image = "images/#{@user.picture_name}"		  
		  open(@user.picture) do |chart|
		     File.open(path_image, 'wb') {|f| f.write chart.read }
		  end
	 	 UserMailer.send_message(path_image,@user,params[:subject],params[:body]).deliver
	 	 File.delete(path_image)
	 	respond_to do |format|
	      format.html { redirect_to root_path }	      
	    end
	 end

	def import_data
		doc = Nokogiri::HTML(open("http://letsgomo.com/meet-our-team/"))
			doc.css(".one-fourth").each do |team_member|				
				name = team_member.at_css(".name").text							
				designation = team_member.at_css("p").text
				picture = team_member.at_css(".photo")[:src]
				User.create_records(name,designation,picture)
			end
		redirect_to root_path	
	end

	def new
		@user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  pic_name = params[:user][:name]+"_"+params[:user][:designation]+".jpg"
	  password = params[:user][:name]+"_"+params[:user][:designation]
	  @user.password = password.downcase
	  @user.password_confirmation = password.downcase
	  @user.picture_name = pic_name.downcase
		if @user.save
			UserMailer.send_invitation(@user,password.downcase).deliver
			redirect_to root_path, notice: 'User has been successfully created'
		else
			render 'new'
		end	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<%= content_tag_for(:li, conversation) do |conversation| %>
  <p>
    <%= link_to conversation.subject, conversation_path(conversation) %>
    |
    <% if conversation.is_completely_trashed?(current_user) %>
      <%= link_to 'Untrash', untrash_conversation_path(conversation), method: :post %>
    <% else %>
      <%= link_to 'Move to trash', trash_conversation_path(conversation), method: :post %>
    <% end %>
  </p>
<% end %>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations ,:html => {:class=>'form-horizontal'} do |f| %>
<fieldset>
    <legend>Send Message</legend>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Recipient</label>
      <div class="col-lg-10">     
        <%= f.text_field :recipients,:class=>"form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Subject</label>
      <div class="col-lg-10">
        <%= f.text_field :subject,:class=>"form-control"%>       
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Body</label>
      <div class="col-lg-10">
        <%= f.text_area :body,:class=>"form-control"%>       
      </div>
    </div>   
     
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="reset" class="btn btn-default">Cancel</button>        
        <%= f.submit "Send" ,:class=>"btn btn-primary"%>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/conversations/index.html.erb
<h1>Conversations</h1>
<h2>Inbox</h2>
<ul>
  <%= render collection: mailbox.inbox, partial: 'conversation' %>
</ul>
<h2>Sentbox</h2>
<ul>
  <%= render collection: mailbox.sentbox, partial: 'conversation' %>
</ul>
<h2>Trash</h2>
<ul>
  <%= render collection: mailbox.trash, partial: 'conversation' %>
</ul>
<%= link_to 'Start Conversation', :new_conversation %>

app/views/conversations/new.html.erb
<h1>Start Conversation</h1>
<%= render 'form' %>

app/views/conversations/show.html.erb
<h1>
  <%= conversation.subject %>
</h1>
<ul>
  <%= content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt| %>
    <% message = receipt.message %>
    <h3>
      <%= message.subject %>
    </h3>
    <p>
      <%= message.body %>
    </p>
  <% end %>
</ul>
<%= render 'messages/form', conversation: conversation %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Letsgomo</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% unless user_signed_in? %>
        <li class="active"><%= link_to "Sign up", new_user_registration_path %><span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Sign in ", new_user_session_path %></li>        
      </ul>
      <%else%>
      <ul class="nav navbar-nav navbar-left">
        <li class="active"><%= link_to "Home",root_path%></li>
      </ul>
      <ul class="nav navbar-nav">      	
        <li><%=link_to "Log out", destroy_user_session_path,method: :delete %></li>                  
      </ul>             
      <%end%>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "View Conversations" ,conversations_path%></li>
      </ul>
    </div>
  </div>
</nav>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for :message, url: reply_conversation_path(conversation),:html => {:class=>'form-horizontal'} do |f| %>
<fieldset>
    <legend>Reply</legend>
   
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Subject</label>
      <div class="col-lg-10">
        <%= f.text_field :subject,:class=>"form-control"%>       
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Body</label>
      <div class="col-lg-10">
        <%= f.text_area :body,:class=>"form-control"%>       
      </div>
    </div>   
     
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="reset" class="btn btn-default">Cancel</button>        
        <%= f.submit "Send" ,:class=>"btn btn-primary"%>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user,:url => users_admin_index_path,:html => {:class => 'form-horizontal'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
 <fieldset>
    <legend>Create User</legend>

    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Name</label>
      <div class="col-lg-10">
        <%= f.text_field :name,:class=>"form-control" %>       
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-10">        
        <%= f.email_field :email, autofocus: true,:class=>"form-control" %>
      </div>
    </div>    

    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Designation</label>
      <div class="col-lg-10">
        <%= f.text_field :designation,:class=>"form-control" %>       
      </div>
    </div>

    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Picture Url</label>
      <div class="col-lg-10">
        <%= f.text_field :picture,:class=>"form-control" %>       
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="reset" class="btn btn-default">Cancel</button>        
        <%= f.submit "Submit" ,:class=>"btn btn-primary"%>
      </div>
    </div>
  </fieldset>
<%end%>

app/views/users/_user.html.erb
<tr>
	<td><%= user.name %></td>
	<td><%= user.email %></td>
	<td><%= user.designation unless user.designation.nil?%></td>    
	<td><%= image_tag user.picture ,size: "100x100" unless user.picture.nil?%></td>    
	<td><%= link_to 'Show', show_path(:id=>user.id) %> |
	<%= link_to 'Delete', destroy_path(:id=>user.id), method: :delete, data: { confirm: 'Are you sure?' } if current_user.is_admin? %></td>    
</tr>

app/views/users/compose_message.html.erb
<%= form_tag send_email_path, multipart: true , :class => 'form-horizontal' do %>

<fieldset>
    <legend>Compose Mail</legend>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-10">        
        <%#= text_field_tag :email, nil,:class=>"form-control" %>
        <%= select_tag :email, options_from_collection_for_select(User.all, "email", "email"), prompt: "Select Email" %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Subject</label>
      <div class="col-lg-10">
        <%= text_field_tag :subject,nil,:class=>"form-control"%>       
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Body</label>
      <div class="col-lg-10">
        <%= text_area_tag :body,nil,:class=>"form-control"%>       
      </div>
    </div>   
     
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="reset" class="btn btn-default">Cancel</button>        
        <%= submit_tag "Send" ,:class=>"btn btn-primary"%>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/users/index.html.erb
<div class="form-inline form-group-dis">
  <div class="bs-example pull-left" data-example-id="btn-tags">
    <% if current_user.is_admin?%>
      <%= link_to('New User', new_users_admin_path,:class => 'btn btn-large btn-primary')  %>
      <%= form_tag import_data_path, :class=>"xyz" do %>
          <%= submit_tag "Import Data",:class=>"btn btn-primary" %>
      <% end %>
    <%end%>
    <%= link_to('Compose Email', compose_message_path,:class => 'btn btn-large btn-primary')  %>    
  </div>

  <div class="form-group pull-right">          
    <%= text_field_tag :q,nil,:placeholder=>"Search",:class=>"form-control"%>
    <%= submit_tag "Submit",:class=>"btn btn-default",:id=>"search-submit"%>
  </div>
</div>

<table class="table table-hover table-bordered">
  <thead>
    <tr>      
      <th>Name</th>
      <th>Email</th>
      <th>Designation</th>
      <th>Picture</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody id="partial_content">
    <%= render(partial: 'user', collection: @users) %>
  </tbody>
</table>

app/views/users/index.js.erb
$('#partial_content').html("<%=j render(partial: 'user', collection: @users, format: 'html') %>");

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="panel-body">
	<dl>
		<dt>Name</dt>
		<dd><%= @user.name %></dd>
		<dt>Email</dt>
		<dd><%= @user.email %></dd>
		<dt>Designation</dt>
		<dd><%= @user.designation unless @user.designation.nil? %></dd>
		<dt>Picture</dt>
		<dd><%= image_tag @user.picture unless @user.picture.nil?%></dd>
  		<dt><%= @user.picture_name unless @user.picture_name.nil?%></dt>
	</dl>
</div>
<%= link_to 'Back', root_path %>